import type { Metadata } from "next";
import { Space_Grotesk, DM_Sans } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/trpc/client";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ConfirmAlertProvider } from "@/components/confirm-alert";
import { Provider } from "jotai";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const dmSans = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${dmSans.variable} font-body antialiased`}
      >
        <NuqsAdapter>
          <Provider>
            <TRPCProvider>
              <ConfirmAlertProvider>{children}</ConfirmAlertProvider>
            </TRPCProvider>
            <Toaster />
          </Provider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
